import fs from "node:fs";
import path from "node:path";
import { runLuaTestFiles } from "reforged-test";
import { describe, expect, it } from "vitest";
import {
  DECLARATIONS_FILE,
  LUA_STUB_FILE,
  generateEditorGlobals,
} from "../../scripts/editor-globals.ts";
import {
  FIXTURE_MAP,
  ROOT,
  copyProject,
  makeTempDir,
  runScript,
} from "./helpers.ts";

const BANNER =
  "Generated by scripts/editor-globals.ts from the map folder's war3map.lua on every install, build and watch.";

/** A 3.0-style script: header, InitGlobals, custom script, unindented trigger functions. */
const SCRIPT = [
  "udg_Score = 0",
  "udg_Rate = 0.0",
  "udg_Hex = 0x10",
  'udg_Name = ""',
  "udg_Flag = false",
  "udg_Kills = __jarray(0)",
  "udg_Speeds = __jarray(0.0)",
  'udg_Names = __jarray("")',
  "udg_Flags = __jarray(false)",
  "udg_Timers = {}",
  "udg_Spots = {}",
  "udg_Group = nil",
  "udg_Players = nil",
  "udg_Hero = nil",
  "udg_Made = CreateTimer()",
  "udg_Weird = 1 + 2",
  "gg_rct_Spawn = nil",
  "gg_cam_Intro = nil",
  "gg_snd_Hit = nil",
  'gg_snd_Theme = "Sound\\\\Music\\\\mp3Music\\\\Comradeship.mp3"',
  "gg_trg_Melee_Initialization = nil",
  "gg_unit_H002_0255 = nil",
  "gg_dest_LTlt_0012 = nil",
  "gg_item_ratf_0003 = nil",
  "gg_qst_Main = nil",
  "  gg_rct_Indented = nil",
  "local udg_Local = 0",
  "gg_rct_Spawn = CreateRegion()",
  "function InitGlobals()",
  "local i = 0",
  "udg_Group = CreateGroup()",
  "udg_Players = CreateForce()",
  "i = 0",
  "while (true) do",
  "if ((i > 1)) then break end",
  "udg_Timers[i] = CreateTimer()",
  "i = i + 1",
  "end",
  "udg_Hero = nil",
  "end",
  "",
  "-- custom script: pasted after InitGlobals, anything at column 0",
  "udg_FromCustom = 5",
  "gg_rct_FromCustom = nil",
  "udg_Hero = CreateUnit(Player(0), FourCC('hfoo'), 0, 0, 0)",
  "",
  "function InitTrig_Melee_Initialization()",
  "gg_trg_Melee_Initialization = CreateTrigger()",
  "gg_rct_Late = nil",
  "end",
].join("\r\n");

const typeOf = (text: string, name: string): string | undefined =>
  generateEditorGlobals(text).globals.find((g) => g.name === name)?.type;

describe("generateEditorGlobals", () => {
  const result = generateEditorGlobals(SCRIPT);
  const types = Object.fromEntries(result.globals.map((g) => [g.name, g.type]));

  it("maps each known gg_ prefix to its handle type", () => {
    expect(types).toMatchObject({
      gg_rct_Spawn: "rect",
      gg_cam_Intro: "camerasetup",
      gg_snd_Hit: "sound",
      gg_trg_Melee_Initialization: "trigger",
      gg_unit_H002_0255: "unit",
      gg_dest_LTlt_0012: "destructable",
      gg_item_ratf_0003: "item",
    });
  });

  it("types a music entry (a gg_snd_ string) as string", () => {
    expect(types.gg_snd_Theme).toBe("string");
  });

  it("declares an unknown gg_ prefix as the root handle type, with a warning", () => {
    expect(types.gg_qst_Main).toBe("handle");
    expect(result.warnings).toContain(
      "gg_qst_Main: unknown editor prefix gg_qst_, declared as handle.",
    );
  });

  it("types udg_ variables from their initializer", () => {
    expect(types).toMatchObject({
      udg_Score: "number",
      udg_Rate: "number",
      udg_Hex: "number",
      udg_Name: "string",
      udg_Flag: "boolean",
      udg_Kills: "Record<number, number>",
      udg_Speeds: "Record<number, number>",
      udg_Names: "Record<number, string>",
      udg_Flags: "Record<number, boolean>",
      // Handles: the Native call the editor assigns in the header or in InitGlobals.
      udg_Made: "NonNullable<ReturnType<typeof CreateTimer>>",
      udg_Group: "NonNullable<ReturnType<typeof CreateGroup>>",
      udg_Players: "NonNullable<ReturnType<typeof CreateForce>>",
      udg_Timers: "Record<number, NonNullable<ReturnType<typeof CreateTimer>>>",
      // Nothing to infer from.
      udg_Hero: "unknown",
      udg_Spots: "Record<number, unknown>",
      udg_Weird: "unknown",
    });
    expect(result.warnings).toContain(
      "udg_Weird: initializer `1 + 2` not recognized, declared as unknown.",
    );
  });

  it("ignores custom script, indented, local and in-function assignments; the first header assignment wins", () => {
    for (const name of [
      "udg_FromCustom",
      "gg_rct_FromCustom",
      "gg_rct_Indented",
      "udg_Local",
      "gg_rct_Late",
    ]) {
      expect(types).not.toHaveProperty(name);
    }
    expect(
      result.globals.filter((g) => g.name === "gg_rct_Spawn"),
    ).toHaveLength(1);
    // udg_Hero's CreateUnit sits in the custom script, after InitGlobals ended.
    expect(types.udg_Hero).toBe("unknown");
  });

  it("reads InitGlobals whether or not the editor indented it", () => {
    const indented =
      "udg_G = nil\nfunction InitGlobals()\n    local i = 0\n    udg_G = CreateGroup()\nend\n";
    expect(typeOf(indented, "udg_G")).toBe(
      "NonNullable<ReturnType<typeof CreateGroup>>",
    );
  });

  it("produces both outputs from one call, one entry per global, with the banner", () => {
    const declarations = result.declarations
      .split("\n")
      .filter((l) => l.startsWith("declare let "));
    const assignments = result.luaStub
      .split("\n")
      .filter((l) => /^(gg|udg)_/.test(l));
    expect(declarations).toHaveLength(result.globals.length);
    expect(assignments).toHaveLength(result.globals.length);
    expect(result.declarations.startsWith(`// ${BANNER}\n`)).toBe(true);
    expect(result.luaStub.startsWith(`-- ${BANNER}\n`)).toBe(true);
    expect(declarations).toContain("declare let gg_rct_Spawn: rect;");
    expect(declarations).toContain(
      "declare let udg_Kills: Record<number, number>;",
    );
  });

  it("stubs every global with nil or its header literal, calling no Native", () => {
    expect(result.luaStub).toContain("\nudg_Score = 0\n");
    expect(result.luaStub).toContain("\nudg_Rate = 0.0\n");
    expect(result.luaStub).toContain('\nudg_Name = ""\n');
    expect(result.luaStub).toContain("\nudg_Flag = false\n");
    expect(result.luaStub).toContain("\nudg_Kills = __jarray(0)\n");
    expect(result.luaStub).toContain("\nudg_Timers = {}\n");
    expect(result.luaStub).toContain("\nudg_Group = nil\n");
    expect(result.luaStub).toContain("\nudg_Made = nil\n");
    expect(result.luaStub).toContain("\ngg_rct_Spawn = nil\n");
    expect(result.luaStub).toContain(
      '\ngg_snd_Theme = "Sound\\\\Music\\\\mp3Music\\\\Comradeship.mp3"\n',
    );
    // Stub authoring rules: none of the libraries the game lacks.
    expect(result.luaStub).not.toMatch(
      /\b(debug|require|package|io|collectgarbage|load)\b|os\.getenv/,
    );
  });

  it("reads the blank map fixture: one trigger, no warnings", () => {
    const fixture = generateEditorGlobals(
      fs.readFileSync(path.join(FIXTURE_MAP, "war3map.lua"), "utf8"),
    );
    expect(fixture.globals).toEqual([
      {
        name: "gg_trg_Melee_Initialization",
        type: "trigger",
        stubValue: "nil",
      },
    ]);
    expect(fixture.warnings).toEqual([]);
  });
});

describe("the generated Lua stub in the reforged-test harness (Lua 5.3)", () => {
  it("loads after the shipped stubs, sets the globals, and adds no call-log line", () => {
    const dir = makeTempDir();
    const stub = path.join(dir, "editor-globals.lua");
    fs.writeFileSync(stub, generateEditorGlobals(SCRIPT).luaStub);
    const outDir = path.join(dir, "out");
    fs.mkdirSync(path.join(outDir, "lua_modules", "reforged-test", "lua"), {
      recursive: true,
    });
    fs.copyFileSync(
      path.join(ROOT, "node_modules", "reforged-test", "lua", "index.lua"),
      path.join(outDir, "lua_modules", "reforged-test", "lua", "index.lua"),
    );
    fs.writeFileSync(
      path.join(outDir, "stub_test.lua"),
      [
        'local t = require("lua_modules.reforged-test.lua.index")',
        't.describe("editor globals", function()',
        '  t.it("has the header values", function()',
        "    t.expect(udg_Score).toBe(0)",
        '    t.expect(udg_Name).toBe("")',
        "    t.expect(udg_Flag).toBe(false)",
        "    t.expect(gg_rct_Spawn).toBe(nil)",
        "    t.expect(udg_Group).toBe(nil)",
        "    t.expect(udg_Kills[7]).toBe(0)",
        "    t.expect(udg_Speeds[3]).toBe(0.0)",
        "    t.expect(udg_Timers[1]).toBe(nil)",
        "    udg_Kills[7] = 3",
        "    t.expect(udg_Kills[7]).toBe(3)",
        "    t.expect(#t.stubCalls()).toBe(0)",
        "  end)",
        "end)",
        "",
      ].join("\n"),
    );

    const file = runLuaTestFiles({ outDir, stubs: [stub] }).at(0);

    expect(file?.error).toBeUndefined();
    expect(file?.tests).toEqual([
      {
        suite: ["editor globals"],
        name: "has the header values",
        status: "pass",
      },
    ]);
  });
});

describe("pnpm build: editor globals", () => {
  const MAP_SCRIPT = path.join(
    "maps",
    "reforged-ts-template.w3m",
    "war3map.lua",
  );

  it("writes both files into the generated folder on the blank map", () => {
    const project = copyProject();

    const result = runScript(project, "scripts/build.ts");

    expect(result.stderr).toBe("");
    expect(result.status).toBe(0);
    const declarations = fs.readFileSync(
      path.join(project, "src", "generated", DECLARATIONS_FILE),
      "utf8",
    );
    const stub = fs.readFileSync(
      path.join(project, "src", "generated", LUA_STUB_FILE),
      "utf8",
    );
    expect(declarations.startsWith(`// ${BANNER}\n`)).toBe(true);
    expect(declarations).toContain(
      "declare let gg_trg_Melee_Initialization: trigger;",
    );
    expect(stub.startsWith(`-- ${BANNER}\n`)).toBe(true);
    expect(stub).toContain("\ngg_trg_Melee_Initialization = nil\n");
  });

  it("fails the type-check on a missing editor global, types an existing one, and picks up a region added in the editor", () => {
    const project = copyProject();
    fs.writeFileSync(
      path.join(project, "src", "uses-globals.ts"),
      [
        "export const trigger: trigger = gg_trg_Melee_Initialization;",
        "export const spawn: rect = gg_rct_Spawn;",
        "",
      ].join("\n"),
    );

    const missing = runScript(project, "scripts/build.ts");
    expect(missing.status).toBe(1);
    expect(missing.stderr).toMatch(
      /uses-globals\.ts\(2,28\): error TS2304: Cannot find name 'gg_rct_Spawn'/,
    );
    expect(missing.stderr).not.toMatch(/uses-globals\.ts\(1,/);

    // The editor saves a new region: the next build declares it.
    const script = path.join(project, MAP_SCRIPT);
    fs.writeFileSync(
      script,
      "gg_rct_Spawn = nil\r\n" + fs.readFileSync(script, "utf8"),
    );
    const added = runScript(project, "scripts/build.ts");
    expect(added.stderr).toBe("");
    expect(added.status).toBe(0);

    // Typed, not any: using the trigger as a number is an error.
    fs.writeFileSync(
      path.join(project, "src", "misuse.ts"),
      "export const n: number = gg_trg_Melee_Initialization;\n",
    );
    const misuse = runScript(project, "scripts/build.ts");
    expect(misuse.status).toBe(1);
    expect(misuse.stderr).toMatch(
      /misuse\.ts\(1,14\): error TS2322: Type 'trigger' is not assignable to type 'number'/,
    );
  });
});
