// The sync script at its entry point: the Template's four synced files as
// shipped, a release payload and fake fetched sources in, the new file
// contents and a change summary out. No network: the fetch is injected.
// Template maintenance, deleted with the sync workflow (see AGENTS.md).
import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import {
  applyRelease,
  LIBRARY_TERMS,
  parsePayload,
  pullRequestNames,
  startMarker,
  SYNCED_FILES,
  syncRepository,
  type FetchText,
  type ReleasePayload,
  type SyncFiles,
} from "../../scripts/sync.ts";
import { LIBRARY_PACKAGES } from "../../scripts/use-local.ts";
import { makeTempDir, runScript, ROOT } from "./helpers.ts";
import { markedBlock, readRepoFile } from "./sync-markers.ts";

/** The four files as the Template ships them. */
const shipped = (): SyncFiles =>
  Object.fromEntries(
    SYNCED_FILES.map((file) => [file, readRepoFile(file)]),
  ) as SyncFiles;

const CONTEXT_URL =
  "https://raw.githubusercontent.com/phmilk/reforged-ts/reforged-ts@1.2.0/CONTEXT.md";
const MATRIX_URL =
  "https://raw.githubusercontent.com/phmilk/reforged-ts/master/release/compatibility/matrix.md";
const LLMS_URL = "https://phmilk.github.io/reforged-ts/1.2/llms.txt";

const payload = (): ReleasePayload => ({
  tag: "reforged-ts@1.2.0",
  versions: {
    "reforged-ts": "1.2.0",
    "reforged-types": "1.1.0",
    "reforged-test": "1.0.3",
    "eslint-plugin-reforged": "1.0.0-alpha.4",
    "reforged-map": "1.0.0-alpha.2",
  },
  contextUrl: CONTEXT_URL,
  matrixUrl: MATRIX_URL,
  llmsUrl: LLMS_URL,
});

const entry = (term: string) =>
  `**${term}**:\nThe library's definition of ${term}.\n_Avoid_: other words for ${term}`;

/**
 * A library CONTEXT.md: its own heading and prose, the fourteen map-author
 * terms in an order unlike the Template's, and library-only terms between.
 */
const LIBRARY_ORDER = [
  "Native",
  "Handle",
  "Wrapper",
  "System",
  "Event descriptor",
  "Subscription",
  "Init stage",
  "Map project",
  "Template",
  "Toolchain",
  "Patch",
  "Rawcode",
  "Object kind",
  "Editor global",
];
const libraryContext = (terms: readonly string[] = LIBRARY_ORDER) =>
  [
    "# reforged-ts",
    "The library's context.",
    "## Language",
    ...terms.slice(0, 2).map(entry),
    entry("Typings"),
    ...terms.slice(2, 7).map(entry),
    entry("Guard"),
    ...terms.slice(7).map(entry),
    entry("Agent skill"),
    "## Relationships",
    "- A **Wrapper** owns one **Handle**.",
  ].join("\n\n") + "\n";

const MATRIX = [
  "<!-- Generated by `pnpm release:matrix` from release/compatibility/matrix.json; do not edit. -->",
  "",
  "| reforged-ts | reforged-types | Patch |",
  "| ----------- | -------------- | ----- |",
  "| 1.2.0       | 1.1.0          | 3.0.0 |",
  "",
].join("\n");

const sources = () => ({ context: libraryContext(), matrix: MATRIX });

const apply = (files = shipped(), release = payload(), fetched = sources()) =>
  applyRelease(files, release, fetched);

/** The lines of `after` that differ from `before`, which must have as many. */
function changedLines(before: string, after: string): string[] {
  const a = before.split("\n");
  const b = after.split("\n");
  expect(b).toHaveLength(a.length);
  return b.filter((line, i) => line !== a[i]);
}

/** `text` with the blocks between its markers (`docs`, `matrix`, `terms`) cut out. */
function outsideBlocks(text: string): string {
  return ["docs", "matrix", "terms"]
    .filter((name) => text.includes(startMarker(name)))
    .reduce((rest, name) => rest.replace(markedBlock(rest, name), ""), text);
}

/**
 * The shipped package.json with the five packages on `^0.0.0`, a range no
 * release writes, so a test sees each of them change whatever the Template
 * ships: the sync workflow runs the tests after applying the release, when
 * a shipped version may already be the payload's.
 */
function unreleasedManifest(): string {
  return LIBRARY_PACKAGES.reduce(
    (text, name) =>
      text.replace(new RegExp(`("${name}": )"[^"]*"`), '$1"^0.0.0"'),
    shipped()["package.json"],
  );
}

describe("the sync's entry point", () => {
  it("sets the five packages to caret ranges on the released versions, nothing else in package.json", () => {
    const before = unreleasedManifest();
    const after = apply({ ...shipped(), "package.json": before }).files[
      "package.json"
    ];
    expect(changedLines(before, after).map((line) => line.trim())).toEqual([
      '"reforged-ts": "^1.2.0",',
      '"reforged-types": "^1.1.0"',
      '"eslint-plugin-reforged": "^1.0.0-alpha.4",',
      '"reforged-map": "^1.0.0-alpha.2",',
      '"reforged-test": "^1.0.3",',
    ]);
    const manifest = JSON.parse(after) as {
      dependencies: Record<string, string>;
      devDependencies: Record<string, string>;
    };
    expect(manifest.dependencies["reforged-ts"]).toBe("^1.2.0");
    expect(manifest.devDependencies["reforged-test"]).toBe("^1.0.3");
  });

  it("writes caret ranges on prerelease versions, nothing else in package.json", () => {
    const manifest = {
      name: "fixture",
      dependencies: {
        "reforged-ts": "^1.0.0-alpha.0",
        "reforged-types": "^1.0.0-alpha.0",
        "other-runtime": "^2.0.0-beta.1",
      },
      devDependencies: {
        "eslint-plugin-reforged": "^1.0.0-alpha.0",
        "reforged-map": "^1.0.0-alpha.0",
        "reforged-test": "^1.0.0-alpha.0",
        "other-dev": "1.0.0-alpha.0",
      },
    };
    const before = JSON.stringify(manifest, null, 2) + "\n";
    const release = payload();
    for (const name of LIBRARY_PACKAGES)
      release.versions[name] = "1.0.0-alpha.3";
    const after = apply({ ...shipped(), "package.json": before }, release)
      .files["package.json"];
    expect(JSON.parse(after)).toEqual({
      ...manifest,
      dependencies: {
        ...manifest.dependencies,
        "reforged-ts": "^1.0.0-alpha.3",
        "reforged-types": "^1.0.0-alpha.3",
      },
      devDependencies: {
        ...manifest.devDependencies,
        "eslint-plugin-reforged": "^1.0.0-alpha.3",
        "reforged-map": "^1.0.0-alpha.3",
        "reforged-test": "^1.0.0-alpha.3",
      },
    });
    expect(changedLines(before, after)).toHaveLength(5);
  });

  it("ships the five packages with caret ranges", () => {
    const manifest = JSON.parse(shipped()["package.json"]) as {
      dependencies: Record<string, string>;
      devDependencies: Record<string, string>;
    };
    const ranges = { ...manifest.dependencies, ...manifest.devDependencies };
    for (const name of LIBRARY_PACKAGES) expect(ranges[name]).toMatch(/^\^\d/);
  });

  it("replaces only the library terms between the CONTEXT.md markers, in the library file's order", () => {
    const before = shipped()["CONTEXT.md"];
    const after = apply().files["CONTEXT.md"];
    expect(outsideBlocks(after)).toBe(outsideBlocks(before));
    const block = markedBlock(after, "terms");
    expect(block).toBe(
      `\n\n## Library terms\n\n${LIBRARY_ORDER.map(entry).join("\n\n")}\n\n`,
    );
  });

  it("takes the fourteen terms whatever order the library lists them in", () => {
    const reversed = [...LIBRARY_ORDER].reverse();
    const block = markedBlock(
      applyRelease(shipped(), payload(), {
        ...sources(),
        context: libraryContext(reversed),
      }).files["CONTEXT.md"],
      "terms",
    );
    expect(
      [...block.matchAll(/^\*\*(.+?)\*\*:$/gm)].map(([, term]) => term),
    ).toEqual(reversed);
    expect([...LIBRARY_TERMS].sort()).toEqual([...LIBRARY_ORDER].sort());
  });

  it("fails, naming the term, when the library's CONTEXT.md lacks one", () => {
    const context = libraryContext(
      LIBRARY_ORDER.filter((term) => term !== "Event descriptor"),
    );
    expect(() =>
      applyRelease(shipped(), payload(), { ...sources(), context }),
    ).toThrow(/Event descriptor/);
  });

  it("replaces the llms.txt link between the docs markers of AGENTS.md and the README, nothing else", () => {
    const { files } = apply();
    for (const file of ["AGENTS.md", "README.md"] as const) {
      const before = shipped()[file];
      const after = files[file];
      expect(outsideBlocks(after), file).toBe(outsideBlocks(before));
      expect(markedBlock(after, "docs"), file).toBe(
        markedBlock(before, "docs").replace(
          /\]\(\S+\/llms\.txt\)/,
          `](${LLMS_URL})`,
        ),
      );
    }
  });

  it("replaces the README's compatibility matrix with the fetched block", () => {
    const before = shipped()["README.md"];
    const after = apply().files["README.md"];
    expect(markedBlock(after, "matrix")).toBe(`\n\n${MATRIX.trim()}\n\n`);
    expect(outsideBlocks(after)).toBe(outsideBlocks(before));
  });

  it("keeps a CRLF file's line endings", () => {
    const files = shipped();
    files["CONTEXT.md"] = files["CONTEXT.md"].replaceAll("\n", "\r\n");
    const after = apply(files).files["CONTEXT.md"];
    expect(after.replaceAll("\r\n", "")).not.toContain("\n");
    expect(after.replaceAll("\r\n", "\n")).toBe(apply().files["CONTEXT.md"]);
  });

  it("returns a file with a missing marker unchanged and names it in the summary", () => {
    const files = shipped();
    files["README.md"] = files["README.md"].replace(
      "<!-- reforged-ts:matrix:end -->\n",
      "",
    );
    files["AGENTS.md"] = files["AGENTS.md"].replace(
      "<!-- reforged-ts:docs:start -->\n",
      "",
    );
    files["CONTEXT.md"] = files["CONTEXT.md"].replace(
      "<!-- reforged-ts:terms:end -->",
      "<!-- reforged-ts:terms:end --> and more",
    );
    const result = apply(files);
    expect(result.files["README.md"]).toBe(files["README.md"]);
    expect(result.files["AGENTS.md"]).toBe(files["AGENTS.md"]);
    expect(result.files["CONTEXT.md"]).toBe(files["CONTEXT.md"]);
    expect(result.changed).toEqual(["package.json"]);
    expect(result.summary).toMatch(
      /`README\.md`.*`<!-- reforged-ts:matrix:end -->`/,
    );
    expect(result.summary).toMatch(
      /`AGENTS\.md`.*`<!-- reforged-ts:docs:start -->`/,
    );
    expect(result.summary).toMatch(
      /`CONTEXT\.md`.*`<!-- reforged-ts:terms:end -->` is not on a line of its own/,
    );
  });

  it("leaves the packages alone outside the dependency sections", () => {
    const files = shipped();
    const withOverrides = (text: string) =>
      text.replace(
        /\n}\n$/,
        ',\n  "pnpm": {\n    "overrides": {\n      "reforged-ts": "1.0.0"\n    }\n  }\n}\n',
      );
    files["package.json"] = withOverrides(files["package.json"]);
    expect(apply(files).files["package.json"]).toBe(
      withOverrides(apply().files["package.json"]),
    );
  });

  it("returns package.json unchanged when a package is not a dependency, and names it", () => {
    const files = shipped();
    files["package.json"] = files["package.json"].replace(
      /\n\s*"reforged-test": "[^"]*",/,
      "",
    );
    const result = apply(files);
    expect(result.files["package.json"]).toBe(files["package.json"]);
    expect(result.summary).toMatch(/`package\.json`.*reforged-test/);
  });

  it("changes nothing when applied again with the same payload", () => {
    const once = apply();
    const twice = apply(once.files);
    expect(twice.files).toEqual(once.files);
    expect(twice.changed).toEqual([]);
    expect(once.changed).toEqual([...SYNCED_FILES]);
  });

  it("summarises the release and every file it changed", () => {
    const { summary } = apply();
    expect(summary).toContain("reforged-ts@1.2.0");
    for (const file of SYNCED_FILES) expect(summary).toContain(`\`${file}\``);
    expect(summary).toContain("`reforged-ts` ^1.2.0");
    expect(summary).toContain(LLMS_URL);
    expect(summary).toContain(CONTEXT_URL);
    expect(summary).toContain(MATRIX_URL);
  });
});

describe("the release payload", () => {
  it("accepts the payload the library's release sends", () => {
    expect(parsePayload(JSON.parse(JSON.stringify(payload())))).toEqual(
      payload(),
    );
  });

  it.each([
    ["no tag", { tag: undefined }, /tag/],
    [
      "a missing version",
      { versions: { ...payload().versions, "reforged-test": undefined } },
      /reforged-test/,
    ],
    [
      "no version of the map reader",
      { versions: { ...payload().versions, "reforged-map": undefined } },
      /reforged-map/,
    ],
    [
      "a version that is not semver",
      { versions: { ...payload().versions, "reforged-ts": "^1.2.0" } },
      /reforged-ts/,
    ],
    [
      "a URL that is not https",
      { contextUrl: "http://x/CONTEXT.md" },
      /contextUrl/,
    ],
    [
      "an llms.txt URL not ending in llms.txt",
      { llmsUrl: "https://phmilk.github.io/reforged-ts/" },
      /llmsUrl/,
    ],
  ])("refuses %s, naming the field", (_, change, message) => {
    expect(() => parsePayload({ ...payload(), ...change })).toThrow(message);
  });

  it.each([
    ["an empty tag", ""],
    ["a tag with ..", "reforged-ts@1..2"],
    ["a tag with a leading .", ".reforged-ts@1.2.0"],
    ["a tag with a trailing .", "reforged-ts@1.2."],
    ["a tag ending in .lock", "reforged-ts@1.2.0.lock"],
    ["a tag with a slash", "reforged-ts/1.2.0"],
    ["a tag with a space", "reforged-ts 1.2.0"],
    ["a tag with a shell character", "v1.2.0;rm"],
    ["a tag with a newline", "v1.2.0\ntitle=x"],
    ["a tag with a reflog brace", "v1.2.0@{1}"],
  ])("refuses %s, naming the tag", (_, tag) => {
    expect(() => parsePayload({ ...payload(), tag })).toThrow(/tag/);
  });

  it.each(["reforged-ts@1.2.0", "v1.2.0-rc.1", "release_1.2"])(
    "accepts the tag %s",
    (tag) => {
      expect(parsePayload({ ...payload(), tag }).tag).toBe(tag);
    },
  );

  it("names the pull request's branch after the tag and its title after the reforged-ts version", () => {
    expect(pullRequestNames(payload())).toEqual({
      branch: "sync/reforged-ts@1.2.0",
      title: "chore(deps): reforged-ts 1.2.0",
    });
  });

  it("titles a release without the library after the package its tag names", () => {
    expect(
      pullRequestNames({ ...payload(), tag: "reforged-types@1.1.0" }),
    ).toEqual({
      branch: "sync/reforged-types@1.1.0",
      title: "chore(deps): reforged-types 1.1.0",
    });
  });

  it.each(["v1.2.0-rc.1", "reforged-types@9.9.9", "other@1.1.0"])(
    "titles the pull request after the reforged-ts version when the tag %s names no released package",
    (tag) => {
      expect(pullRequestNames({ ...payload(), tag }).title).toBe(
        "chore(deps): reforged-ts 1.2.0",
      );
    },
  );
});

describe("the sync on a repository", () => {
  /** A temporary copy of the four files, as the workflow's checkout has them. */
  function checkout(): string {
    const root = makeTempDir();
    for (const file of SYNCED_FILES)
      fs.copyFileSync(path.join(ROOT, file), path.join(root, file));
    return root;
  }

  it("fetches the payload's two URLs and writes the new files", async () => {
    const root = checkout();
    const fetched: string[] = [];
    const fetchText: FetchText = (url) => {
      fetched.push(url);
      return Promise.resolve(url === CONTEXT_URL ? libraryContext() : MATRIX);
    };
    const result = await syncRepository(root, payload(), fetchText);
    expect(fetched.sort()).toEqual([CONTEXT_URL, MATRIX_URL].sort());
    for (const file of SYNCED_FILES)
      expect(fs.readFileSync(path.join(root, file), "utf8")).toBe(
        result.files[file],
      );
    expect(result).toEqual(apply());
  });

  it("writes nothing when a fetch fails", async () => {
    const root = checkout();
    await expect(
      syncRepository(root, payload(), () =>
        Promise.reject(new Error("404 Not Found")),
      ),
    ).rejects.toThrow(/404/);
    for (const file of SYNCED_FILES)
      expect(fs.readFileSync(path.join(root, file), "utf8")).toBe(
        fs.readFileSync(path.join(ROOT, file), "utf8"),
      );
  });
});

describe("the sync command", () => {
  it("prints the usage when run without a payload file", () => {
    const result = runScript(ROOT, "scripts/sync.ts");
    expect(result.status).toBe(1);
    expect(result.stderr).toContain("Usage:");
  });

  it("names the field when the payload file is invalid, before fetching anything", () => {
    const dir = makeTempDir();
    const file = path.join(dir, "payload.json");
    fs.writeFileSync(file, JSON.stringify({ ...payload(), tag: "" }));
    const result = runScript(dir, path.join(ROOT, "scripts/sync.ts"), [file]);
    expect(result.status).toBe(1);
    expect(result.stderr).toMatch(/sync failed: .*tag/);
  });

  it("sets no step output when the tag cannot name a branch", () => {
    const dir = makeTempDir();
    const file = path.join(dir, "payload.json");
    const outputs = path.join(dir, "github-output");
    fs.writeFileSync(file, JSON.stringify({ ...payload(), tag: "a..b" }));
    fs.writeFileSync(outputs, "");
    const result = runScript(dir, path.join(ROOT, "scripts/sync.ts"), [file], {
      GITHUB_OUTPUT: outputs,
    });
    expect(result.status).toBe(1);
    expect(result.stderr).toMatch(
      /sync failed: .*`tag` cannot name a git branch/,
    );
    expect(fs.readFileSync(outputs, "utf8")).toBe("");
  });
});

/** The jobs of a workflow's text, by id: each job's lines up to the next. */
function jobs(workflow: string): Map<string, string> {
  const block = workflow.slice(workflow.indexOf("\njobs:\n"));
  const starts = [...block.matchAll(/^ {2}([a-z-]+):\n/gm)];
  return new Map(
    starts.map(({ 1: id, index }, i) => [
      id,
      block.slice(index, starts[i + 1]?.index),
    ]),
  );
}

describe("the sync workflow", () => {
  const workflow = readRepoFile(".github/workflows/sync.yml");

  it("reads the App's key in no job outside the environment board, in any workflow", () => {
    const dir = path.join(ROOT, ".github/workflows");
    for (const file of fs.readdirSync(dir)) {
      for (const [id, job] of jobs(readRepoFile(`.github/workflows/${file}`)))
        if (job.includes("APP_PRIVATE_KEY"))
          expect(job, `${file}: ${id}`).toMatch(/^ {4}environment: board$/m);
    }
  });

  it("runs the install, build and check in a job without secrets", () => {
    const sync = jobs(workflow).get("sync") ?? "";
    expect(sync).toContain("pnpm check");
    expect(sync).not.toMatch(/secrets\./);
    expect(sync).not.toMatch(/^ {4}environment:/m);
  });

  it("opens the pull request on main alone, in the environment board, after the sync", () => {
    const pullRequest = jobs(workflow).get("pull-request") ?? "";
    expect(pullRequest).toMatch(/^ {4}needs: sync$/m);
    expect(pullRequest).toMatch(
      /^ {4}if: github\.repository == 'phmilk\/reforged-ts-template' && github\.ref == 'refs\/heads\/main'$/m,
    );
    expect(pullRequest).toMatch(/^ {4}environment: board$/m);
    expect(pullRequest).toContain("peter-evans/create-pull-request");
    // No install: the job holding the key runs no third-party code.
    expect(pullRequest).not.toMatch(/pnpm\/action-setup|\bpnpm [a-z]/);
  });
});
