import fs from "node:fs";
import path from "node:path";
import { generateEditorGlobals, MapFolderError } from "reforged-map";
import {
  CONFIG_FILE,
  loadConfig,
  type Mode,
  type ResolvedConfig,
} from "./config.ts";
import { runAsEntry } from "./cli.ts";
import { AuthorError } from "./errors.ts";

/** One file the pipeline writes into the generated folder. */
export interface GeneratedFile {
  /** File name relative to the generated folder (`env.ts`). */
  name: string;
  contents: string;
}

/** Receives an author-facing warning (never an error). */
export type Warn = (message: string) => void;

/**
 * Produces generated files from the resolved configuration, reporting
 * warnings through `warn`. Add a writer to `GENERATORS` to have it run
 * everywhere.
 */
export type Generator = (config: ResolvedConfig, warn: Warn) => GeneratedFile[];

/** The default `warn`: `Warning: <message>` on stderr. */
export const printWarning: Warn = (message) => {
  console.warn(`Warning: ${message}`);
};

/** Opening comment of every generated TypeScript file. */
export const GENERATED_BANNER =
  "// Generated by the build pipeline (scripts/generate.ts). Do not edit: every install, build and watch rewrites it.\n";

export const ENV_FILE = "env.ts";

/** The env file's text: one boolean, `devMode`, which the entry passes to `Reforged.configure`. */
export function envFileContents(mode: Mode): string {
  return `${GENERATED_BANNER}\n/** On in \`dev\` builds (the library's runtime checks run), off in \`release\` builds. Set by \`--mode\` or \`mode\` in ${CONFIG_FILE}. */\nexport const devMode: boolean = ${String(mode === "dev")};\n`;
}

export const generateEnv: Generator = (config) => [
  { name: ENV_FILE, contents: envFileContents(config.mode) },
];

/**
 * The Editor globals of the map folder, which `reforged-map` declares from its
 * `war3map.lua` and `war3map.wtg`: `editor-globals.d.ts` for the map's code
 * and `editor-globals.lua` for the harness. Its warnings go to `warn`; a map
 * folder it cannot read (missing, or without `war3map.lua`) is an AuthorError
 * with the package's message.
 */
export const generateEditorGlobalsFiles: Generator = (config, warn) => {
  let output: ReturnType<typeof generateEditorGlobals>;
  try {
    output = generateEditorGlobals(config.mapFolder);
  } catch (error) {
    if (error instanceof MapFolderError) throw new AuthorError(error.message);
    throw error;
  }
  for (const warning of output.warnings) warn(warning);
  return output.files;
};

/** Every writer, run in order by install (`prepare`), every build and the watch. */
export const GENERATORS: readonly Generator[] = [
  generateEnv,
  generateEditorGlobalsFiles,
];

/**
 * Writes every generator's files into the generated folder, creating it if
 * needed. A file whose text is unchanged is not rewritten, so a watch on the
 * source folder is not re-triggered. Returns the absolute paths it produced.
 */
export function generate(
  config: ResolvedConfig,
  generators: readonly Generator[] = GENERATORS,
  warn: Warn = printWarning,
): string[] {
  fs.mkdirSync(config.generatedFolder, { recursive: true });
  const written: string[] = [];
  for (const generator of generators) {
    for (const file of generator(config, warn)) {
      const target = path.join(config.generatedFolder, file.name);
      if (path.dirname(target) !== config.generatedFolder) {
        throw new Error(
          `Generated file name must be a bare file name, got ${JSON.stringify(file.name)}.`,
        );
      }
      const current = fs.existsSync(target)
        ? fs.readFileSync(target, "utf8")
        : undefined;
      if (current !== file.contents) fs.writeFileSync(target, file.contents);
      written.push(target);
    }
  }
  return written;
}

/** Command line: `node scripts/generate.ts [--mode dev|release]` (the `prepare` script), run from the repository root. */
await runAsEntry(import.meta.url, "Generate", async () => {
  const config = await loadConfig(
    path.resolve(CONFIG_FILE),
    process.argv.slice(2),
  );
  const files = generate(config);
  console.log(
    `Generated ${files.map((file) => path.relative(config.root, file)).join(", ")} (mode ${config.mode})`,
  );
});
